### ISSUE TITLE
Select Instructions

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#27]

**Comment by mfekadu** [comment]
The plan:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/11131250/64460015-57b41600-d0c7-11e9-90fc-a9c2eb96f474.png">

**Comment by mfekadu** [comment]
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/11131250/64460145-aa8dcd80-d0c7-11e9-9054-3fc42699f188.png">

**Comment by mfekadu** [comment]
useful video related to liveness analysis: https://youtu.be/4eHdo8GaICY

**Comment by mfekadu** [comment]
It looks like we can ignore type for now, but it will matter for Garbage collection:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/11131250/64460520-91395100-d0c8-11e9-8be8-645bca3079a0.png">

**Comment by mfekadu** [comment]
**Example input**
```racket
> (explicate-control '(program () (if #t 1 2)))
'(program
  ()
  ((start (if (eq? #t #t) (goto block174) (goto block175)))
   (block175 (return 2))
   (block174 (return 1))))
> (explicate-control '(program () (let [[x (if #t 2 3)]] x)))
'(program
  ()
  ((block176 (return x))
   (start (if (eq? #t #t) (goto block177) (goto block178)))
   (block178 (seq (assign x 3) (goto block176)))
   (block177 (seq (assign x 2) (goto block176)))))
>
```

## TODO: 
- [ ] consider how the "block" construct of make-interference will be affected
- [ ] consider same for uncover-live
- [x] have handle-arg change `#t -> 1` and `#f -> 0`

**Comment by mfekadu** [comment]
<img width="757" alt="image" src="https://user-images.githubusercontent.com/11131250/64462771-94840b00-d0cf-11e9-8cc9-b53a287906ac.png">

**Comment by mfekadu** [comment]
😢  #35
