### ISSUE TITLE
Uncover live

### ISSUE THREAD

**Issue by johnvtan** [mfekadu/rc#28]
**TODO**
- [x] uncover-live should handle bools `#t` `#f`
  * `edit:` not needed because `select-instructions` converts bools to 1 or 0
- [ ] uncover-live should handle handle new x86 constructs (see below)
  * `edit:` perhaps no changes/few changes needed here because uncover-live helpers are written generally and perviously the special cases were `addq` and `negq` and it doesn't seem like any new special cases were introduced in R2
- [x] uncover-live should work with multiple blocks (not just 1)
  - [x] calculate the live-after-sets for all blocks/branches on Control-Flow-Graph
    - [x] **_no successor block_** means **_empty live-after-set_**
    - [x] **_∃ successor block_** means **_calculate live-after-sets for successors first_**
    - [x] If you reach a branch then _union the live-after-sets of all of the successor blocks_

**Example Input**
```racket
> p
'(program
  ()
  ((block176 (return x))
   (start (if (eq? #t #t) (goto block177) (goto block178)))
   (block178 (seq (assign x 3) (goto block176)))
   (block177 (seq (assign x 2) (goto block176)))))

> (select-instructions p)
'(program
  ()
  ((label block176)
   (movq (var x) (reg rax))
   (jmp conclusion)
   (label start)
   (cmpq (int 1) (int 1))
   (jmp-if e block177)
   (jmp block178)
   (label block178)
   (movq (int 3) (var x))
   (jmp block176)
   (label block177)
   (movq (int 2) (var x))
   (jmp block176)))
>
```
* consider the `start` block. 
  * It has a successor `block178`
    * which has a successor `block176`
      * which has **no successors**... let's call it a "**_basic block_**"
        * which has `life-after-set = {}`
* Fun facts:
  * the input program is a _Control-Flow-Graph_ and is a _Directed-Acyclic-Graph_

**Algorithm**
* calculate the live-after-sets in _**reverse topological order**_ starting from the "basic blocks"
  * `tsort` and `transpose` functions exist in [`graph`](https://docs.racket-lang.org/graph/index.html) and could be useful for this purpose.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/11131250/64494362-df318e80-d259-11e9-92a9-3ad7aa30df35.png">

**Comment by mfekadu** [comment]
**```> ./run programs/if-should-exit-42.rc```**
```racket
uncover-live: Bad x86_0 program (program (complex-op1164 complex-if1166 complex-op1165) ((label block1168) (movq (int 44) (reg rax)) (jmp conclusion) (label block1167) (movq (int 42) (reg rax)) (jmp conclusion) (label start) (cmpq (int 2) (int 1)) (set l (byte-reg al)) (movzbq (byte-reg al) (var complex-op1164)) (cmpq (var complex-op1164) (int 1)) (jmp-if e block1170) (jmp block1171) (label block1171) (cmpq (int 2) (int 1)) (set e (byte-reg al)) (movzbq (byte-reg al) (var complex-op1165)) (cmpq (int 0) (var complex-op1165)) (set e (byte-reg al)) (movzbq (byte-reg al) (var complex-if1166)) (jmp block1169) (label block1170) (movq (int 0) (var complex-if1166)) (jmp block1169) (label block1169) (cmpq (var complex-if1166) (int 1)) (jmp-if e block1167) (jmp block1168)))
  context...:
   "/Users/mfekadu/GitHub/rc/compiler.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    do_stuff()
  File "build.py", line 24, in do_stuff
    subprocess.run(compile_args, stdout=output, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./compiler.rkt', 'programs/if-should-exit-42.rc']' returned non-zero exit status 1.
>
```

**Comment by mfekadu** [comment]
```racket
> (select-instructions p)
'(program
  ()
  ((label block176)
   (movq (var x) (reg rax))
   (jmp conclusion)
   (label start)
   (cmpq (int 1) (int 1))
   (jmp-if e block177)
   (jmp block178)
   (label block178)
   (movq (int 3) (var x))
   (jmp block176)
   (label block177)
   (movq (int 2) (var x))
   (jmp block176)))
```

This above code is the current format of the input into uncover-live. It's flat, unlike the input into select-instructions (see the first comment on this issue). 

**Let's reformat the input to look like this:**
```racket
'(program
  ()
  ( ((label block176)
      (movq (var x) (reg rax))
      (jmp conclusion))
    ((label start)
     (cmpq (int 1) (int 1))
     (jmp-if e block177)
     (jmp block178))
    ((label block178)
     (movq (int 3) (var x))
     (jmp block176))
    ((label block177)
     (movq (int 2) (var x))
     (jmp block176))))
```

This alternative formatting will allow uncover-live to easily parse through the labels to then find which blocks to branch into. As a result, we can create a control-flow-graph that would look like this (using [`graph`](https://docs.racket-lang.org/graph/index.html)):
```racket
(define edges '((start block177 block178) (block177 block176) (block178 block176)))
(define g (unweighted-graph/adj edges) )
```


Such that the following the graph `g` has the following properties
```racket
> (has-edge? g 'start 'block177)
#t
> (has-edge? g 'start 'block178)
#t
> (has-edge? g 'start 'block176)
#f
> (has-edge? g 'block176 'block178)
#f
> (has-edge? g 'block178 'block176)
#t
```

**And most importantly**
```racket
> (dag? g)
#t
``` 



# 
#
#

**An idea for getting the block names to make "edges" in the adjacency list**

Consider this block:
```racket
> blocks
'(((label block176) (movq (var x) (reg rax)) (jmp conclusion))
  ((label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
  ((label block178) (movq (int 3) (var x)) (jmp block176))
  ((label block177) (movq (int 2) (var x)) (jmp block176)))
```

The second of that list is the _start_ block which branches into 2 other blocks
```racket
> (second blocks)
'((label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
```

Get the name of that block
```racket
> (second (first (second blocks)))
'start
```

Get the other 2 blocks
```racket
> (filter (lambda (arg) (string-prefix? arg "block"))  (rest (map to-string (flatten (second blocks)))))
'("block177" "block178")
```

But convert them to symbols
```racket
> (map string->symbol (filter (lambda (arg) (string-prefix? arg "block"))  (rest (map to-string (flatten (second blocks))))))
'(block177 block178)
>
```

The benefit of working with a `flatten`ed representation of the structured blocks is that we don't have to use `match` or any code specific to R2, just for making this adjacency matrix. This part of the code hopefully won't need to change as we upgrade the compiler in the future. 

Now it's easy to imagine creating the following list to be a part of the adjacency matrix:
```racket
'(start block177 block178)
```


#
#
#

**Another alternative**

```racket
> blocks
'((label block176)
  (movq (var x) (reg rax))
  (jmp conclusion)
  (label start)
  (cmpq (int 1) (int 1))
  (jmp-if e block177)
  (jmp block178)
  (label block178)
  (movq (int 3) (var x))
  (jmp block176)
  (label block177)
  (movq (int 2) (var x))
  (jmp block176))

> (foldr (lambda (elem acc) (match elem [`(label ,b) (cons elem acc)][_ #:when (not (empty? acc)) (cons (cons (first acc) elem) (rest acc))][_ acc])) '() blocks)
'((label block176)
  (((label start) jmp conclusion) movq (var x) (reg rax))
  ((((label block178) jmp block178) jmp-if e block177) cmpq (int 1) (int 1))
  (((label block177) jmp block176) movq (int 3) (var x)))
```

**Comment by mfekadu** [comment]
**Given**
```racket
> p
'(program ()
           ((block176 (return x))
            (start (if (eq? #t #t) (goto block177) (goto block178)))
            (block178 (seq (assign x 3) (goto block176)))
            (block177 (seq (assign x 2) (goto block176)))))
```

**New Expectation from Select-Instructions**
```racket
> (displayln (select-instructions p))
'(program ()
         ((block () (label block177) (movq (int 2) (var x)) (jmp block176))
          (block () (label block178) (movq (int 3) (var x)) (jmp block176))
          (block () (label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
          (block () (label block176) (movq (var x) (reg rax)) (jmp conclusion))))
```

#

The above is implemented by fb9a8fe

**Comment by mfekadu** [comment]
The most difficult part turns out to be organizing the blocks for 2 purposes:

1. because `get-live-after-sets` only works on a list of instructions from a _single block_
  * so a new helper function is needed to `get-LAS-from-blocks` 
    * LAS=Live-After-Sets
  * the book describes the trick to deciding “_what’s alive_” after a branch is to just say “_both blocks are alive_” (i.e. _union the LAS from all successor blocks_)

2. to form a graph because apparently [`tsort`][1] (topological sort) and [`transpose`][2] could be helpful. 
  * a `tsort`ed graph can serve as an auxiliary to the aforementioned `get-LAS-from-blocks` function to make sure that the “_start_” block is ordered last and preceded by any successor blocks within the DAG (CFG) because LAS are calculated in reverse order.

**TODO:**
- [x] make the function `get-LAS-from-blocks`
  - [ ] **given** _list of blocks_ and _an ordered list of labels_ _an ordered list of edges_ **output** the LAS
    * nah
  - [ ] **_Alternative:_** **given** a _already-reverse-topologically-sorted list of blocks_ **output** the LAS
    * nope
  - [x] `edit: September 10, 2019` decided on 
   * **given** _hash table of blocks_ such that keys are block-label-names and values are the entire `(block ,info ,instrs ...)` construct
   * **also given** _graph_: which is a DAG that represents the CFG in the way described below in the "Consider the graph" section...
   * **output**: a list of blocks with all the right things in all the right places

**`get-LAS-from-blocks` output**
```racket
'((block
    (#<set: x> #<set: x> #<set:> #<set:>)
    (label block176) (movq (var x) (reg rax)) (jmp conclusion))
 (block
    (#<set:> #<set:> #<set:> #<set:>)
    (label block178) (movq (int 3) (var x)) (jmp block176))
 (block
    (#<set:> #<set:> #<set:> #<set:>)
    (label block177) (movq (int 2) (var x)) (jmp block176))
 (block
    (#<set:> #<set:> #<set:> #<set:> #<set:>)
    (label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178)))
```
* notice there are too many sets inside each block
* the length of the list of sets should be equal to the length of the list of instructions
  * but the subsequent pass is aware of this and takes care of it so that's fine
#

**Consider the graph `g` with the following vertices and edges**
```racket
> (get-vertices g)
(block176 block178 start block177)
```
```racket
> (get-edges g)
((block178 block176) (start block177) (start block178) (block177 block176))
```

**the `tsort` of `g` is this list of vertices**
```racket
> (tsort g)
(start block177 block178 block176)
```

**`reverse` then `tsort` is the same as `tsort` then `transpose`**
```racket
> (reverse (tsort g))
(block176 block178 block177 start)
```
```racket
> (tsort (transpose g))
(block176 block178 block177 start)
```
* but the difference is that transpose

  * > ["Returns a new graph where the **edges** of the **original graph** are **reversed**"][2]


#
#

**Some more cool racket**
**Fun Fact:** [`filter-map`][3] is more efficient than `filter` + `map`
```racket
> start
'(block () (label start) (cmpq (int 1) (int 1)) (jmp-if e block177) (jmp block178))
```
```racket
> (filter (λ (x) (member (car x) '(label jmp jmp-if))) (drop start 2))
'((label start) (jmp-if e block177) (jmp block178))
```

**inefficient**
```racket
> (map last (filter (λ (x) (member (car x) '(label jmp jmp-if))) (drop start 2)))
(list 'start 'block177 'block178)
```

**efficient && also a much cleaner way to calculate `get-adj-list` [fb9a8fe]**
```racket
> (filter-map (λ (x) (and (member (car x) '(label jmp jmp-if)) (last x))) (drop start 2))
(list 'start 'block177 'block178)
```

[1]: https://docs.racket-lang.org/graph/index.html#%28def._%28%28lib._graph%2Fmain..rkt%29._tsort%29%29
[2]: https://docs.racket-lang.org/graph/index.html#%28def._%28%28lib._graph%2Fmain..rkt%29._transpose%29%29
[3]: https://docs.racket-lang.org/reference/pairs.html#%28def._%28%28lib._racket%2Flist..rkt%29._filter-map%29%29
